function setRCPPointsVectors()
    global reta1Xvector reta1Yvector
    global reta2Xvector reta2Yvector
    global reta3Xvector reta3Yvector
    global reta4Xvector reta4Yvector
    global reta5Xvector reta5Yvector
    global reta6Xvector reta6Yvector
    global reta7Xvector reta7Yvector
    global reta8Xvector reta8Yvector
    global reta9Xvector reta9Yvector
    global reta10Xvector reta10Yvector
    
    global Xarc1 Yarc1
    global Xarc2 Yarc2
    global Xarc3 Yarc3
    global Xarc4 Yarc4
    global Xarc5 Yarc5
    global Xarc6 Yarc6
    global Xarc7 Yarc7
    global Xarc8 Yarc8
    global Xarc9 Yarc9
    global Xarc10 Yarc10
    
    global LineA1B1x LineA1B1y
    global LineB2C1x LineB2C1y
    global LineC2D1x LineC2D1y
    global LineD2E1x LineD2E1y
    global LineE2F1x LineE2F1y
    global LineF2G1x LineF2G1y
    global LineG2H1x LineG2H1y
    global LineH2I1x LineH2I1y
    global LineI2J1x LineI2J1y
    global LineJ2A2x LineJ2A2y
    
    PontosX = [reta1Xvector, Xarc2, ...
               reta2Xvector, Xarc3, ...
               reta3Xvector, Xarc4, ...
               reta4Xvector, Xarc5, ...
               reta5Xvector, Xarc6, ...
               reta6Xvector, Xarc7, ...
               reta7Xvector, Xarc8, ...
               reta8Xvector, Xarc9, ...
               reta9Xvector, Xarc10, ...
               reta10Xvector, Xarc1];
    
    PontosY = [reta1Yvector, Yarc2, ...
               reta2Yvector, Yarc3, ...
               reta3Yvector, Yarc4, ...
               reta4Yvector, Yarc5, ...
               reta5Yvector, Yarc6, ...
               reta6Yvector, Yarc7, ...
               reta7Yvector, Yarc8, ...
               reta8Yvector, Yarc9, ...
               reta9Yvector, Yarc10, ...
               reta10Yvector, Yarc1];

%     PontosX = [LineA1B1x, Xarc2, ...
%                LineB2C1x, Xarc3, ...
%                LineC2D1x, Xarc4, ...
%                LineD2E1x, Xarc5, ...
%                LineE2F1x, Xarc6, ...
%                LineF2G1x, Xarc7, ...
%                LineG2H1x, Xarc8, ...
%                LineH2I1x, Xarc9, ...
%                LineI2J1x, Xarc10, ...
%                LineJ2A2x, Xarc1];
% 
%     PontosY = [LineA1B1y, Yarc2, ...
%                LineB2C1y, Yarc3, ...
%                LineC2D1y, Yarc4, ...
%                LineD2E1y, Yarc5, ...
%                LineE2F1y, Yarc6, ...
%                LineF2G1y, Yarc7, ...
%                LineG2H1y, Yarc8, ...
%                LineH2I1y, Yarc9, ...
%                LineI2J1y, Yarc10, ...
%                LineJ2A2y, Yarc1];

      

   
    
           
           
%            
%            
%            
%     PontosX = [LineA1B1x, Xarc2, ...
%                LineB2C1x, Xarc3, ...
%                LineC2D1x, Xarc4];
% 
%     PontosY = [LineA1B1y, Yarc2, ...
%                LineB2C1y, Yarc3, ...
%                LineC2D1y, Yarc4];           
           
%            



%     figure(22)
%     image_filename = 'rcp2.png';
%     background_image = imread(image_filename);
%     imshow(background_image);
%     hold on
%     plot(PontosX, PontosY, '-g')
end