function h1 = drawArrowV2(h1, VPlotHandler, x0,y0,angulo)
    % x0 = 1
    % y0 = 1
    % angulo = 45
    length = 1;
    ArrowLength = 20;
    try
        delete(VPlotHandler)
    catch
    end
    
%     arrow('Parent',ax1, 'ObjectHandles', 'Start',[xrotated,yrotated], ...
%             'Stop',[xrotated+Alength*cosd(thetad),yrotated+Alength*sind(thetad)],...
%             'Type','line',...
%             'Color','r',...
%             'Length',20);
    try
    [h1,~,~] = arrow('Parent',h1, 'ObjectHandles',VPlotHandler,...
                    'Start',[x0,y0], ...
                    'Stop',[x0+length*cosd(angulo),y0+length*sind(angulo)],...
                    'Type','line',...
                    'Color','r',...
                    'Length',ArrowLength)
    catch
end

